runtime: custom
env: flex

manual_scaling:
   instances: 1

resources:
   cpu: 1
   memory_gb: 1
   disk_size_gb: 10

readiness_check:
   path: /api/health
   check_interval_sec: 5
   timeout_sec: 5
   failure_threshold: 2
   success_threshold: 2
   app_start_timeout_sec: 600

env_variables:
   MB_DB_TYPE: mysql
   MB_DB_DBNAME: metabase
   MB_DB_HOST: 172.17.0.1

beta_settings:
  cloud_sql_instances: <cloud-sql-connection>=tcp:3306

includes:
  - secret.yaml
